<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Faq', 'doctrine');

/**
 * BaseFaq
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $content
 * @property string $lang
 * @property string $meta_title
 * @property string $meta_desc
 * @property string $meta_keywrds
 * @property boolean $published
 * 
 * @method string  getTitle()        Returns the current record's "title" value
 * @method string  getContent()      Returns the current record's "content" value
 * @method string  getLang()         Returns the current record's "lang" value
 * @method string  getMetaTitle()    Returns the current record's "meta_title" value
 * @method string  getMetaDesc()     Returns the current record's "meta_desc" value
 * @method string  getMetaKeywrds()  Returns the current record's "meta_keywrds" value
 * @method boolean getPublished()    Returns the current record's "published" value
 * @method Faq     setTitle()        Sets the current record's "title" value
 * @method Faq     setContent()      Sets the current record's "content" value
 * @method Faq     setLang()         Sets the current record's "lang" value
 * @method Faq     setMetaTitle()    Sets the current record's "meta_title" value
 * @method Faq     setMetaDesc()     Sets the current record's "meta_desc" value
 * @method Faq     setMetaKeywrds()  Sets the current record's "meta_keywrds" value
 * @method Faq     setPublished()    Sets the current record's "published" value
 * 
 * @package    cartefinancement
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFaq extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('faq');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('content', 'string', 65535, array(
             'type' => 'string',
             'length' => 65535,
             ));
        $this->hasColumn('lang', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 'fr',
             'length' => 255,
             ));
        $this->hasColumn('meta_title', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('meta_desc', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('meta_keywrds', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('published', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $versionable0 = new Doctrine_Template_Versionable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'unique' => true,
             'uniqueBy' => 
             array(
              0 => 'lang',
             ),
             'fields' => 
             array(
              0 => 'title',
             ),
             'canUpdate' => true,
             ));
        $this->actAs($timestampable0);
        $this->actAs($versionable0);
        $this->actAs($sluggable0);
    }
}