<?php

/**
 * CategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Category');
    }
    
    /*
     *  Lorsque l'on récupère une catégorie, on veut aussi récupérer ses actus
     * et triées dans le bon ordre
     */
    public static function getCategoryBySlug($slug)
    {
      $q = self::getInstance()->createQuery("c")
        ->leftJoin("c.News n")
        ->where("c.slug = ?", $slug)
        ->addWhere("n.published = 1")
        ->orderBy("n.flag desc")
        ->addOrderBy("n.created_at desc");
      return $q->execute()->getFirst();
    }
}