<?php

/**
 * FaqTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FaqTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FaqTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Faq');
    }
    
    public static function getLatest($count = null, $lang = 'fr')
    {
      $q = self::getInstance()
        ->createQuery('f')
        ->where('f.published = 1')
        ->andWhere('f.lang = ?', $lang)
        ->orderBy('f.created_at desc');
      if($count)
        $q->limit($count);
      return $q->execute();
    }
    
    public static function getPublished($lang = 'fr')
    {
      return self::getInstance()
        ->createQuery('f')
        ->where('f.published = 1')
        ->andWhere('f.lang = ?', $lang)
        ->orderBy('f.created_at desc')
        ->execute();
    }
}