<?php

/**
 * News
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    cartefinancement
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class News extends BaseNews
{
  public function getCategoryName()
  {
    return $this->getCategory()->getName();
  }
  
  public function getCategorySlug()
  { 
    return CarteFinancement::slugify($this->getCategory());
  }
  
  public function hasImage()
  {
    $img = trim($this->getImage());
    return !empty($img);
  }
  
  public function getImagePath()
  {
    if(!$this->hasImage())
      return null;
    return '/uploads/news/' . $this->getImage();
  }

}