<?php

/**
 * StandAlone
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    cartefinancement
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class StandAlone extends BaseStandAlone
{
  public function isHome()
  {
    return $this->getIsHome() == 1;
  }
  
  // TODO: à tester !!  c'est récursif
  public function getRoot()
  {
    if($this->getParentId() == null)
      return $this;
    
    return $this->getParent()->getRoot();
  }
  
  public function hasChildren()
  {
    return count($this->getChildren()) > 0;
  }
  
  public function isFork()
  {
    return $this->getFork() == 1;
  }
  
  // A utiliser avec une route particulière, genre /:href, pour générer les URLs
  // La route pour parser les URLs doit être précisée avant, du meme type, mais /:slug
  public function getHref()
  {
    if($this->isFork())
    {
      $firstPage = $this->getChildren()->getFirst();
      return $firstPage ? $firstPage->getHref() : null;
    }
    else
    {
      return $this->getSlug();
    }
  }
  
  // Le H1 vaut par défaut 'title', s'il n'est pas renseigné
  public function getH1()
  {
    $h1 = $this->_get('h1');
    return $h1 ? : $this->getTitle();
  }
}