<?php

/**
 * StandAloneTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StandAloneTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object StandAloneTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('StandAlone');
    }
    
    public static function findHomePage($culture)
    {
      // les deux homepages françaises et anglaises ont un nom terminant par '_:sf_culture'
      return self::getInstance()
        ->createQuery('s')
        ->where('s.is_home = ?', 1)
        ->andWhere('s.page_id like ?', '%_'.$culture)
        ->execute()
        ->getFirst();
    }
}