generator:
  class: sfDoctrineGenerator
  param:
    model_class:           news
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          news
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [lang, category_name, title, flag, created_at, published]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
