<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version8 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('stand_alone', 'baseline');
    }

    public function down()
    {
        $this->addColumn('stand_alone', 'baseline', 'string', '255', array(
             'notnull' => '',
             ));
    }
}