<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version6 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('stand_alone', 'page_id', 'string', '255', array(
             'unique' => '1',
             'notnull' => '1',
             ));
    }

    public function down()
    {
        $this->removeColumn('stand_alone', 'page_id');
    }
}