<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version10 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropForeignKey('faq', 'faq_faq_cat_id_faq_cat_id');
    }

    public function down()
    {
        $this->createForeignKey('faq', 'faq_faq_cat_id_faq_cat_id', array(
             'name' => 'faq_faq_cat_id_faq_cat_id',
             'local' => 'faq_cat_id',
             'foreign' => 'id',
             'foreignTable' => 'faq_cat',
             'onUpdate' => '',
             'onDelete' => 'SET NULL',
             ));
    }
}