<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version4 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropTable('product');
        $this->dropTable('product_cat');
        $this->dropTable('product_content');
        $this->dropTable('product_version');
        $this->dropTable('product_content_version');
        $this->removeColumn('faq_cat', 'product_id');
        $this->removeColumn('news_tag', 'product_id');
        $this->addColumn('stand_alone', 'menu_order', 'integer', '8', array(
             'default' => '1',
             ));
        $this->addColumn('stand_alone', 'is_main_section', 'boolean', '25', array(
             'default' => '0',
             ));
    }

    public function down()
    {
        $this->createTable('product', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'title' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'sub_title' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'summary' => 
             array(
              'type' => 'string',
              'length' => '65535',
             ),
             'image_name' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'category_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'version' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             ), array(
             'type' => 'INNODB',
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('product_cat', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'title' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'sub_title' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             ), array(
             'type' => 'INNODB',
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('product_content', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'title' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'product_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             'parent_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'menu_order' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             'meta_title' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'meta_desc' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'meta_keywds' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'content' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '65535',
             ),
             'devis_btn_text' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'is_main_section' => 
             array(
              'type' => 'boolean',
              'default' => '0',
              'length' => '25',
             ),
             'summary' => 
             array(
              'type' => 'string',
              'length' => '65535',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'version' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'slug' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             ), array(
             'type' => 'INNODB',
             'indexes' => 
             array(
              'product_content_sluggable' => 
              array(
              'fields' => 
              array(
               0 => 'slug',
               1 => 'product_id',
              ),
              'type' => 'unique',
              ),
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('product_version', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'primary' => '1',
             ),
             'title' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'sub_title' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'summary' => 
             array(
              'type' => 'string',
              'length' => '65535',
             ),
             'image_name' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'category_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'version' => 
             array(
              'primary' => '1',
              'type' => 'integer',
              'length' => '8',
             ),
             ), array(
             'type' => 'INNODB',
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
              1 => 'version',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('product_content_version', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'primary' => '1',
             ),
             'title' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'product_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             'parent_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'menu_order' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             'meta_title' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'meta_desc' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'meta_keywds' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'content' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '65535',
             ),
             'devis_btn_text' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'is_main_section' => 
             array(
              'type' => 'boolean',
              'default' => '0',
              'length' => '25',
             ),
             'summary' => 
             array(
              'type' => 'string',
              'length' => '65535',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'version' => 
             array(
              'primary' => '1',
              'type' => 'integer',
              'length' => '8',
             ),
             ), array(
             'type' => 'INNODB',
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
              1 => 'version',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
        $this->addColumn('faq_cat', 'product_id', 'integer', '8', array(
             ));
        $this->addColumn('news_tag', 'product_id', 'integer', '8', array(
             ));
        $this->removeColumn('stand_alone', 'menu_order');
        $this->removeColumn('stand_alone', 'is_main_section');
    }
}