<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version12 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('faq', 'image_name');
        $this->removeColumn('faq', 'faq_cat_id');
        $this->removeColumn('news', 'image_name');
        $this->removeColumn('faq_version', 'image_name');
        $this->removeColumn('faq_version', 'faq_cat_id');
        $this->removeColumn('news_version', 'image_name');
    }

    public function down()
    {
        $this->addColumn('faq', 'image_name', 'string', '255', array(
             ));
        $this->addColumn('faq', 'faq_cat_id', 'integer', '8', array(
             ));
        $this->addColumn('news', 'image_name', 'string', '255', array(
             ));
        $this->addColumn('faq_version', 'image_name', 'string', '255', array(
             ));
        $this->addColumn('faq_version', 'faq_cat_id', 'integer', '8', array(
             ));
        $this->addColumn('news_version', 'image_name', 'string', '255', array(
             ));
    }
}