<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version9 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('stand_alone', 'h1', 'string', '255', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('stand_alone', 'h1');
    }
}