<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version3 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropTable('whoarewe');
        $this->createTable('stand_alone', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'title' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'slug' => 
             array(
              'type' => 'string',
              'unique' => '1',
              'length' => '255',
             ),
             'is_home' => 
             array(
              'type' => 'boolean',
              'default' => '0',
              'length' => '25',
             ),
             'meta_title' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'meta_desc' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'meta_keywrds' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'baseline' => 
             array(
              'type' => 'string',
              'notnull' => '',
              'length' => '255',
             ),
             'content' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '65535',
             ),
             ), array(
             'type' => 'INNODB',
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->createTable('whoarewe', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'title' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'meta_title' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'meta_desc' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'meta_keywrds' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'baseline' => 
             array(
              'type' => 'string',
              'notnull' => '',
              'length' => '255',
             ),
             'content' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '65535',
             ),
             ), array(
             'type' => 'INNODB',
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
        $this->dropTable('stand_alone');
    }
}