<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version7 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('stand_alone', 'fork', 'boolean', '25', array(
             'default' => '0',
             ));
        $this->changeColumn('stand_alone', 'content', 'string', '65535', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('stand_alone', 'fork');
    }
}