<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version18 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('faq', 'lang', 'string', '255', array(
             'notnull' => '1',
             'default' => 'fr',
             ));
        $this->addColumn('faq_version', 'lang', 'string', '255', array(
             'notnull' => '1',
             'default' => 'fr',
             ));
    }

    public function down()
    {
        $this->removeColumn('faq', 'lang');
        $this->removeColumn('faq_version', 'lang');
    }
}