<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version21 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('news', 'image', 'string', '255', array(
             'notnull' => '',
             ));
        $this->addColumn('news_version', 'image', 'string', '255', array(
             'notnull' => '',
             ));
    }

    public function down()
    {
        $this->removeColumn('news', 'image');
        $this->removeColumn('news_version', 'image');
    }
}