<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version22 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('news', 'flag', 'integer', '8', array(
             'notnull' => '',
             ));
        $this->addColumn('news_version', 'flag', 'integer', '8', array(
             'notnull' => '',
             ));
    }

    public function down()
    {
        $this->removeColumn('news', 'flag');
        $this->removeColumn('news_version', 'flag');
    }
}