<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version24 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('category', 'lang', 'string', '255', array(
             'notnull' => '1',
             'default' => 'fr',
             ));
        $this->addColumn('news', 'lang', 'string', '255', array(
             'notnull' => '1',
             'default' => 'fr',
             ));
        $this->addColumn('news_version', 'lang', 'string', '255', array(
             'notnull' => '1',
             'default' => 'fr',
             ));
    }
    
    public function down()
    {
        $this->removeColumn('category', 'lang');
        $this->removeColumn('news', 'lang');
        $this->removeColumn('news_version', 'lang');
    }
}