<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version26 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('news', 'flag', 'boolean', '25', array(
             'default' => '0',
             ));
        $this->changeColumn('news_version', 'flag', 'boolean', '25', array(
             'default' => '0',
             ));
    }
    
    public function postUp()
    {
      $newsList = NewsTable::getInstance()->findAll();
      foreach($newsList as $news)
        $news->setFlag(0);
      $newsList->save();
    }

    public function down()
    {

    }
}